export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export type FETCH_CLIENTS = typeof FETCH_CLIENTS;

export const FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED';
export type FETCH_CLIENTS_FAILED = typeof FETCH_CLIENTS_FAILED;

export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export type FETCH_CLIENTS_SUCCESS = typeof FETCH_CLIENTS_SUCCESS;

export const ADD_CLIENT = 'ADD_CLIENT';
export type ADD_CLIENT = typeof ADD_CLIENT;

export const ADD_CLIENT_FAILED = 'ADD_CLIENT_FAILED';
export type ADD_CLIENT_FAILED = typeof ADD_CLIENT_FAILED;

export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export type ADD_CLIENT_SUCCESS = typeof ADD_CLIENT_SUCCESS;

export const EDIT_CLIENT = 'EDIT_CLIENT';
export type EDIT_CLIENT = typeof EDIT_CLIENT;

export const EDIT_CLIENT_FAILED = 'EDIT_CLIENT_FAILED';
export type EDIT_CLIENT_FAILED = typeof EDIT_CLIENT_FAILED;

export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export type EDIT_CLIENT_SUCCESS = typeof EDIT_CLIENT_SUCCESS;
