export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export type FETCH_CLIENTS = typeof FETCH_CLIENTS;

export const FETCH_CLIENTS_FAILED = 'FETCH_CLIENTS_FAILED';
export type FETCH_CLIENTS_FAILED = typeof FETCH_CLIENTS_FAILED;

export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export type FETCH_CLIENTS_SUCCESS = typeof FETCH_CLIENTS_SUCCESS;
