export const SELECT_ORDER_BLUEPRINT = 'SELECT_ORDER_BLUEPRINT';
export type SELECT_ORDER_BLUEPRINT = typeof SELECT_ORDER_BLUEPRINT;

export const ADD_ORDER_BLUEPRINT = 'ADD_ORDER_BLUEPRINT';
export type ADD_ORDER_BLUEPRINT = typeof ADD_ORDER_BLUEPRINT;

export const DELETE_ORDER_BLUEPRINT = 'DELETE_ORDER_BLUEPRINT';
export type DELETE_ORDER_BLUEPRINT = typeof DELETE_ORDER_BLUEPRINT;

export const SAVE_ORDER_BLUEPRINT = 'SAVE_ORDER_BLUEPRINT';
export type SAVE_ORDER_BLUEPRINT = typeof SAVE_ORDER_BLUEPRINT;
