export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export type FETCH_PRODUCTS = typeof FETCH_PRODUCTS;

export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';
export type FETCH_PRODUCTS_FAILED = typeof FETCH_PRODUCTS_FAILED;

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export type FETCH_PRODUCTS_SUCCESS = typeof FETCH_PRODUCTS_SUCCESS;
